### ISSUE TITLE
Error when building the package

### ISSUE THREAD

**Issue by mohammad-h-b** [MIT-SPARK/Kimera-VIO-ROS#130]
**Description:**
When trying to build the package I get the error message of two same package names.

**Command:**
```
catkin build
```

**Console output:**
```
(base) mohammad@mohammad:~/catkin_ws/src$ catkin build
-------------------------------------------------------------
Profile:                     default
Extending:        [explicit] /opt/ros/melodic
Workspace:                   /home/mohammad/catkin_ws
-------------------------------------------------------------
Build Space:        [exists] /home/mohammad/catkin_ws/build
Devel Space:        [exists] /home/mohammad/catkin_ws/devel
Install Space:      [unused] /home/mohammad/catkin_ws/install
Log Space:          [exists] /home/mohammad/catkin_ws/logs
Source Space:       [exists] /home/mohammad/catkin_ws/src
DESTDIR:            [unused] None
-------------------------------------------------------------
Devel Space Layout:          merged
Install Space Layout:        None
-------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------------


-------------------------------------------------------------
WARNING: Your workspace is configured to explicitly extend a
workspace which yields a CMAKE_PREFIX_PATH which is
different from the cached CMAKE_PREFIX_PATH used last time
this workspace was built.

If you want to use a different CMAKE_PREFIX_PATH you should
call `catkin clean` to remove all references to the previous
CMAKE_PREFIX_PATH.

Cached CMAKE_PREFIX_PATH:
	/home/mohammad/catkin_ws/devel
Other workspace to extend:
	/opt/ros/melodic
Other workspace's CMAKE_PREFIX_PATH:
	/opt/ros/melodic
-------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/bin/catkin", line 11, in <module>
    load_entry_point('catkin-tools==0.6.1', 'console_scripts', 'catkin')()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 272, in main
    catkin_main(sysargs)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 267, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 422, in main
    summarize_build=opts.summarize  # Can be True, False, or None
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 283, in build_isolated_workspace
    workspace_packages = find_packages(context.source_space_abs, exclude_subspaces=True, warnings=[])
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 96, in find_packages
    raise RuntimeError('\n'.join(duplicates))
RuntimeError: Multiple packages found with the same name "numpy_eigen":
- numpy_eigen
- schweizer_messer/numpy_eigen
```

Please give also the following information:
* Operating system and version (e.g. Ubuntu 16.04 or Windows 10): Ubuntu 18.04
* Did you change the source code? (yes / no): no

**Comment by ToniRV** [comment]
Hi @mohammad-h-b , just do:
`touch CATKIN_IGNORE` either on the numpy_eigen package or the schweizer_messer/numpy_eigen one.
I wonder why you have these packages though...
